force-app/main/default/objects/Lead_Score_Criteria__mdt/Lead_Score_Criteria__mdt.object-meta.xml
<CustomObject>
    <description>Criteria for scoring Leads</description>
    <label>Lead Score Criteria</label>
    <pluralLabel>Lead Score Criteria</pluralLabel>
</CustomObject>

force-app/main/default/objects/Lead_Score_Criteria__mdt/fields/End_Value__c.field-meta.xml
<CustomField>
    <fullName>End_Value__c</fullName>
    <description>The end value of the range (used only for &apos;Between&apos; operator)</description>
    <label>End Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Score_Criteria__mdt/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <description>Field to compare with the value</description>
    <label>Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Score_Criteria__mdt/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <description>The operator to use for comparison</description>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Equals</fullName>
                <default>true</default>
                <label>Equals</label>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
            <value>
                <fullName>GreaterThan</fullName>
            </value>
            <value>
                <fullName>LessThan</fullName>
            </value>
            <value>
                <fullName>IsBlank</fullName>
            </value>
            <value>
                <fullName>IsNotBlank</fullName>
            </value>
            <value>
                <fullName>Between</fullName>
            </value>
            <value>
                <fullName>NotContains</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Score_Criteria__mdt/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <description>The score to assign if the condition is met.</description>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Score_Criteria__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>The value to compare against</description>
    <label>Value</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/LeadServiceTest.cls
@IsTest
private with sharing class LeadServiceTest {
    @IsTest
    private static void testLeadScoreCalculationForContainsAndNotContains() {
        List<Lead_Score_Criteria__mdt> leadScoreCriteriaList = new List<Lead_Score_Criteria__mdt>();
        leadScoreCriteriaList.add(
            new Lead_Score_Criteria__mdt(
                Field__c = 'Email',
                Operator__c = 'NotContains',
                Value__c = 'yahoo.com, gmail.com',
                Score__c = 25
            )
        );

        leadScoreCriteriaList.add(
            new Lead_Score_Criteria__mdt(
                Field__c = 'Title',
                Operator__c = 'Contains',
                Value__c = 'Head,VP',
                Score__c = 25
            )
        );

        Lead leadRecord = new Lead(Email = 'test@test.com', Title = 'Head of Sales');
        LeadService.leadScoreCriteriaList = leadScoreCriteriaList;

        Test.startTest();
        Integer leadScore = LeadService.calculateLeadScore(leadRecord);
        Test.stopTest();

        System.Assert.areEqual(50, leadScore, 'Lead score should be 50');
    }

    @IsTest
    private static void testLeadScoreCalculationForContainsAndNotContainsNegative() {
        List<Lead_Score_Criteria__mdt> leadScoreCriteriaList = new List<Lead_Score_Criteria__mdt>();
        leadScoreCriteriaList.add(
            new Lead_Score_Criteria__mdt(
                Field__c = 'Email',
                Operator__c = 'NotContains',
                Value__c = 'yahoo.com, gmail.com',
                Score__c = 25
            )
        );

        leadScoreCriteriaList.add(
            new Lead_Score_Criteria__mdt(
                Field__c = 'Title',
                Operator__c = 'Contains',
                Value__c = 'Head,VP',
                Score__c = 25
            )
        );

        Lead leadRecord = new Lead(Email = 'test@gmail.com', Title = '');
        LeadService.leadScoreCriteriaList = leadScoreCriteriaList;

        Test.startTest();
        Integer leadScore = LeadService.calculateLeadScore(leadRecord);
        Test.stopTest();

        System.Assert.areEqual(0, leadScore, 'Lead score should be 0');
    }

    @IsTest
    private static void testLeadScoreCalculationForEqualsIsBlankAndIsNotBlank() {
        List<Lead_Score_Criteria__mdt> leadScoreCriteriaList = new List<Lead_Score_Criteria__mdt>();
        leadScoreCriteriaList.add(
            new Lead_Score_Criteria__mdt(
                Field__c = 'Email',
                Operator__c = 'Equals',
                Value__c = 'test@test.com',
                Score__c = 25
            )
        );

        leadScoreCriteriaList.add(
            new Lead_Score_Criteria__mdt(Field__c = 'Phone', Operator__c = 'IsNotBlank', Score__c = 25)
        );

        leadScoreCriteriaList.add(
            new Lead_Score_Criteria__mdt(Field__c = 'Title', Operator__c = 'IsBlank', Score__c = 25)
        );

        Lead leadRecord = new Lead(Email = 'test@test.com', Phone = '1234567890', Title = '');

        LeadService.leadScoreCriteriaList = leadScoreCriteriaList;

        Test.startTest();
        Integer leadScore = LeadService.calculateLeadScore(leadRecord);
        Test.stopTest();

        System.Assert.areEqual(75, leadScore, 'Lead score should be 75');
    }

    @IsTest
    private static void testLeadScoreCalculationForGreaterThan() {
        List<Lead_Score_Criteria__mdt> leadScoreCriteriaList = new List<Lead_Score_Criteria__mdt>();
        leadScoreCriteriaList.add(
            new Lead_Score_Criteria__mdt(
                Field__c = 'NumberOfEmployees',
                Operator__c = 'GreaterThan',
                Value__c = '999',
                Score__c = 25
            )
        );

        Lead leadRecord = new Lead(NumberOfEmployees = 1000);
        LeadService.leadScoreCriteriaList = leadScoreCriteriaList;

        Test.startTest();
        Integer leadScore = LeadService.calculateLeadScore(leadRecord);
        Test.stopTest();

        System.Assert.areEqual(25, leadScore, 'Lead score should be 25');
    }

    @IsTest
    private static void testLeadScoreCalculationForBetween() {
        List<Lead_Score_Criteria__mdt> leadScoreCriteriaList = new List<Lead_Score_Criteria__mdt>();
        leadScoreCriteriaList.add(
            new Lead_Score_Criteria__mdt(
                Field__c = 'NumberOfEmployees',
                Operator__c = 'Between',
                Value__c = '499',
                End_Value__c = '1000',
                Score__c = 20
            )
        );

        Lead leadRecord = new Lead(NumberOfEmployees = 999);
        LeadService.leadScoreCriteriaList = leadScoreCriteriaList;

        Test.startTest();
        Integer leadScore = LeadService.calculateLeadScore(leadRecord);
        Test.stopTest();

        System.Assert.areEqual(20, leadScore, 'Lead score should be 25');
    }

    @IsTest
    private static void testLeadScoreCalculationForLessThan() {
        List<Lead_Score_Criteria__mdt> leadScoreCriteriaList = new List<Lead_Score_Criteria__mdt>();
        leadScoreCriteriaList.add(
            new Lead_Score_Criteria__mdt(
                Field__c = 'NumberOfEmployees',
                Operator__c = 'LessThan',
                Value__c = '1000',
                Score__c = 20
            )
        );

        Lead leadRecord = new Lead(NumberOfEmployees = 999);
        LeadService.leadScoreCriteriaList = leadScoreCriteriaList;

        Test.startTest();
        Integer leadScore = LeadService.calculateLeadScore(leadRecord);
        Test.stopTest();

        System.Assert.areEqual(20, leadScore, 'Lead score should be 25');
    }
}